apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-api
spec:
  selector:
    matchLabels:
      app: todo-app-api
  replicas: 3
  template:
    metadata:
      labels:
        app: todo-app-api
    spec:
      containers:
        - name: node-api
          image: hieunguyenxk/app-backend
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: ME_CONFIG_MONGODB_SERVER
              valueFrom:
                configMapKeyRef:
                  name: mongo-config
                  key: mongo-url
            - name: ME_CONFIG_MONGODB_ADMINUSERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo-user
            - name: ME_CONFIG_MONGODB_ADMINPASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo-password
          # env:
          #   - name: MONGO_URL
          #     value: mongodb+srv://hieunguyen:0comatkhau@cluster0.1g7anct.mongodb.net/
---
apiVersion: v1
kind: Service
metadata:
  name: todo-app-api
spec:
  selector:
    app: todo-app-api
  ports:
    - port: 5000
      protocol: TCP
      targetPort: 5000
  